name: WorldEngine
main: com.liamxsage.worldengine.WorldEngine
version: ${version}
description: "WorldManagement kept ahead of the curve, always planning a step further"
author: "LiamXSage"
api-version: "1.21"
loader: com.liamxsage.worldengine.DependencyLoader
bootstrapper: com.liamxsage.worldengine.CommandBootstrapper
load: STARTUP